# Generated by Django 4.2.1 on 2023-05-18 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctionlist_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlist',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 14, 54, 11, 585173)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 14, 54, 11, 585173)),
        ),
    ]
