# Generated by Django 4.2.1 on 2023-05-18 17:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auctionlisting_category_auctionlisting_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('CSA', 'Clothing and Accessories'), ('SPT', 'Sports'), ('HM', 'Home'), ('ELT', 'Electronics'), ('TY', 'Toys'), ('BMD', 'Books and Media'), ('HAB', 'Health and Beauty'), ('OTH', 'Others')], max_length=64),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 22, 42, 28, 433038)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 22, 42, 28, 434034)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 18, 22, 42, 28, 434034)),
        ),
    ]
