# Generated by Django 4.2.1 on 2023-05-19 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 21, 1, 58, 519394)),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='image_url',
            field=models.ImageField(blank=True, default='asd', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 21, 1, 58, 520391)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 19, 21, 1, 58, 520391)),
        ),
    ]
