# Generated by Django 4.2.1 on 2023-05-20 15:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='category',
            field=models.CharField(choices=[('CSA', 'Clothing and Accessories'), ('SPT', 'Sports'), ('HM', 'Home'), ('ELT', 'Electronics'), ('TY', 'Toys'), ('BMD', 'Books and Media'), ('HAB', 'Health and Beauty'), ('OTH', 'Others')], default='srsr', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 20, 15, 18, 409329)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 20, 15, 18, 409329)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 20, 20, 15, 18, 409329)),
        ),
    ]
