# Generated by Django 4.2.1 on 2023-05-24 08:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_alter_auctionlisting_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='second_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='auctionlisting',
            name='third_image',
            field=models.ImageField(default='images/default.jpg', upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='auctionlisting',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 13, 42, 35, 794925)),
        ),
        migrations.AlterField(
            model_name='bid',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 13, 42, 35, 794925)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 24, 13, 42, 35, 794925)),
        ),
    ]
